global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'pm2-metrics'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9209']
